/* Refresh the baked food grids inside index.html from tools/baked-foods.js.
   Run food-import.mjs first; this only moves the result between the markers,
   so new models are two commands away from being in someone's hands:
     node tools/food-import.mjs
     node tools/splice-foods.mjs                                           */
import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const IDX = join(ROOT, 'index.html');
const A = '/*==== BAKED FOOD VOX';
const B = '/*==== END BAKED FOOD VOX ====*/';
const html = readFileSync(IDX, 'utf8');
const baked = readFileSync(join(ROOT, 'tools', 'baked-foods.js'), 'utf8');
const i0 = html.indexOf(A), i1 = html.indexOf(B);
if (i0 < 0 || i1 < 0) throw new Error('markers not found in index.html');
const head = html.slice(0, i0), tail = html.slice(i1 + B.length);
const block =
`/*==== BAKED FOOD VOX (generated by tools/food-import.mjs) =================
  The street food, reduced to role grids by the same pipeline the weapons
  came through - surface-voxelised, flood-solidified, colour-classified
  with food-first thresholds so a bun is bread and a tomato is a light.
  Re-run the importer and tools/splice-foods.mjs to refresh; consumables
  without a baked entry keep their procedural rigItem shapes.
==========================================================================*/
` + baked + B;
writeFileSync(IDX, head + block + tail);
console.log('respliced ' + (baked.length / 1024).toFixed(0) + 'KB into index.html');
