/* Refresh the baked weapon grids inside index.html from tools/baked-guns.js.
   Run gun-import.mjs first; this only moves the result between the markers,
   so new models are two commands away from being in the game:
     node tools/gun-import.mjs
     node tools/splice-guns.mjs                                            */
import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const IDX = join(ROOT, 'index.html');
const A = '/*==== BAKED WEAPON VOX';
const B = '/*==== END BAKED WEAPON VOX ====*/';
const html = readFileSync(IDX, 'utf8');
const baked = readFileSync(join(ROOT, 'tools', 'baked-guns.js'), 'utf8');
const i0 = html.indexOf(A), i1 = html.indexOf(B);
if (i0 < 0 || i1 < 0) throw new Error('markers not found in index.html');
const head = html.slice(0, i0), tail = html.slice(i1 + B.length);
const block =
`/*==== BAKED WEAPON VOX (generated by tools/gun-import.mjs) ================
  Real models, reduced to role grids: surface-voxelised at sub-cell steps,
  flood-solidified so nothing is a shell, bright paint handed to the
  emissive roles so the red and the green on a gun are LIGHTS. Re-run the
  importer and tools/splice-guns.mjs to refresh; weapons without a baked
  entry keep their authored box lists.
==========================================================================*/
` + baked + B;
writeFileSync(IDX, head + block + tail);
console.log('respliced ' + (baked.length / 1024).toFixed(0) + 'KB into index.html');
